name: Control Dockerfiles
on:
  push:
    paths:
      - 'Dockerfile*'
      - '.github/workflows/build-dockerfile.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["armv7hf", "aarch64"]
    steps:
      - name: Checkout repo source code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Control that Dockerfile builds
        uses: docker/build-push-action@v4
        with:
          file: "Dockerfile.${{ matrix.arch }}"
          push: false
